name: Owo Selfbot 6h Cron

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install discord.js-selfbot-v13 dotenv
      - run: |
          node bot.js &
          sleep 21600
          pkill -f "node bot.js" || true
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          SOCIAL_USER_ID: ${{ secrets.SOCIAL_USER_ID }}
